In [1]:
import numpy as np

In [3]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [4]:
print(iris[:10])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [19]:
print(np.unique(iris[:,4]))

[b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica']


In [20]:
iris_species = np.unique(iris[:,4])[:2]

In [21]:
print(iris_species)

[b'Iris-setosa' b'Iris-versicolor']


In [24]:
iris2 = iris[np.where((iris[:,4] == iris_species[0])|(iris[:,4] ==iris_species[1]))]

In [26]:
print(np.unique(iris2[:,4]))

[b'Iris-setosa' b'Iris-versicolor']


In [31]:
Iris_setosa_data = iris2[np.where((iris2[:,4] == iris_species[0]))]

In [32]:
Iris_versicolor_data = iris2[np.where((iris2[:,4] == iris_species[1]))]

In [34]:
print(Iris_setosa_data[:5])
print(Iris_versicolor_data[:5])

print(Iris_setosa_data.shape)
print(Iris_versicolor_data.shape)

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']]
[[b'7.0' b'3.2' b'4.7' b'1.4' b'Iris-versicolor']
 [b'6.4' b'3.2' b'4.5' b'1.5' b'Iris-versicolor']
 [b'6.9' b'3.1' b'4.9' b'1.5' b'Iris-versicolor']
 [b'5.5' b'2.3' b'4.0' b'1.3' b'Iris-versicolor']
 [b'6.5' b'2.8' b'4.6' b'1.5' b'Iris-versicolor']]
(50, 5)
(50, 5)


In [39]:
label_setosa = np.zeros([Iris_setosa_data.shape[0],1])

In [40]:
label_versicolor = np.ones([Iris_versicolor_data.shape[0],1])

In [42]:
Iris_setosa_data = np.hstack((Iris_setosa_data,label_setosa))

In [43]:
print(Iris_setosa_data[:5])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa' 0.0]
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa' 0.0]
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa' 0.0]
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa' 0.0]
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa' 0.0]]


In [44]:
Iris_versicolor_data = np.hstack((Iris_versicolor_data,label_versicolor))

In [45]:
print(Iris_versicolor_data[:5])

[[b'7.0' b'3.2' b'4.7' b'1.4' b'Iris-versicolor' 1.0]
 [b'6.4' b'3.2' b'4.5' b'1.5' b'Iris-versicolor' 1.0]
 [b'6.9' b'3.1' b'4.9' b'1.5' b'Iris-versicolor' 1.0]
 [b'5.5' b'2.3' b'4.0' b'1.3' b'Iris-versicolor' 1.0]
 [b'6.5' b'2.8' b'4.6' b'1.5' b'Iris-versicolor' 1.0]]


In [46]:
iris2 = np.vstack((Iris_setosa_data,Iris_versicolor_data))

In [47]:
print(np.unique(iris2[:,4]))

[b'Iris-setosa' b'Iris-versicolor']


In [48]:
def sigmoid_fun(x):
    return 1/(1+np.exp(-x))

In [49]:
print(sigmoid_fun(2))

0.8807970779778823


In [56]:
print(sigmoid_fun(np.array([1,32,5,-1,-20,0])))

[0.73105858 1.         0.99330715 0.26894142 0.         0.5       ]


In [55]:
np.set_printoptions(suppress=True)

In [97]:
def feedforward_fun(Theta,X):
#     Theta and X must be matrix (np.array().shape = 2,1)
    rows = np.shape(X)[0]
    Z = np.array([np.dot(Theta,X[i]) for i in range(rows)])
    return sigmoid_fun(Z)

In [99]:
feedforward_fun(np.array([1,1]),np.array([[1,2],[5,3]]))

array([0.95257413, 0.99966465])

In [174]:
def cost_fun(Theta, X, Y_label):
    h_q = feedforward_fun(Theta, X)
    
#     print('h_q shape:',h_q.shape)
#     print('h_q:',h_q)
    cost = Y_label*np.log(h_q)+ (1-Y_label)*np.log(1-h_q)
    return -np.sum(cost)/X.shape[0]

In [103]:
print(cost_fun(np.array([1,2,1,1]),np.array([[1,1,1,1],[2,3,2,1]]),np.array([0,1])))

-5.006732050050455


In [154]:
print(np.array([1,2,1,1]).reshape(-1,1))

[[1]
 [2]
 [1]
 [1]]


In [85]:
print(iris2[:5])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa' 0.0]
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa' 0.0]
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa' 0.0]
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa' 0.0]
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa' 0.0]]


In [89]:
iris2_data = iris2[:,[0,1,2,3,5]]

In [90]:
print(iris2_data[:5])

[[b'5.1' b'3.5' b'1.4' b'0.2' 0.0]
 [b'4.9' b'3.0' b'1.4' b'0.2' 0.0]
 [b'4.7' b'3.2' b'1.3' b'0.2' 0.0]
 [b'4.6' b'3.1' b'1.5' b'0.2' 0.0]
 [b'5.0' b'3.6' b'1.4' b'0.2' 0.0]]


In [94]:
iris2_data = iris2_data.astype('float64')

In [95]:
print(iris2_data[:5])

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]]


In [110]:
print(iris2_data[:,:3][:5])
print(iris2_data[:,4][:5])

[[5.1 3.5 1.4]
 [4.9 3.  1.4]
 [4.7 3.2 1.3]
 [4.6 3.1 1.5]
 [5.  3.6 1.4]]
[0. 0. 0. 0. 0.]


In [121]:
Theta = np.array([0.0,0.0,0.0,0.0])


In [122]:
Theta[0] = Theta[0]+0.01

In [123]:
Theta.dtype

dtype('float64')

In [124]:
print(Theta)

[0.01 0.   0.   0.  ]


In [125]:
iris2_data[:5]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ]])

In [131]:
sample_indexs = np.random.choice(iris2_data.shape[0],iris2_data.shape[0]//2)

In [132]:
train_data = iris2_data[sample_indexs] 

In [145]:
print(train_data[:,4][:5])
print(train_data[:,:4][:5])

[1. 1. 0. 0. 1.]
[[6.5 2.8 4.6 1.5]
 [6.3 2.5 4.9 1.5]
 [4.5 2.3 1.3 0.3]
 [5.1 3.8 1.6 0.2]
 [5.5 2.6 4.4 1.2]]


Training process

In [204]:
if __name__ == '__main__':
    
    
    Theta = np.array([0.0,0.0,0.0,0.0])
    
    X = train_data[:,:4]
    Y_label = train_data[:,4]
    learning_rate = 0.01
    dirac_x = 0.0001
    
    diff = 100000
    previous_cost = 0
    while True:
        Theta_list = []
        current_cost = cost_fun(Theta,X,Y_label)
        print('current_cost:',current_cost)
        if abs(previous_cost - current_cost)<=0.00001:
            break
        for i in range(Theta.shape[0]):
#             compute gradiant
            Theta_cp = Theta
            Theta_cp[i] = Theta_cp[i] + dirac_x
            cost_lambda = cost_fun(Theta_cp,X,Y_label)
            gradiant = (cost_lambda-current_cost)/dirac_x
            theta_tmp = Theta[i] - learning_rate*gradiant
            Theta_list.append(theta_tmp)
            
        previous_cost = current_cost
        Theta = np.array(Theta_list)
        print('current Theta:',Theta)
    print('training is over!')
    print('optimal parameters are:',Theta)

current_cost: 0.6931471805599453
current Theta: [0.00853603 0.01027068 0.02058217 0.02419902]
current_cost: 0.6578969469947452
current Theta: [0.01467441 0.01691582 0.03604694 0.04282865]
current_cost: 0.6362486150177363
current Theta: [0.01909626 0.02096685 0.04784683 0.05746874]
current_cost: 0.6221955875732291
current Theta: [0.02228871 0.02316141 0.05702064 0.06924917]
current_cost: 0.6124894485102043
current Theta: [0.02459441 0.02401852 0.0642989  0.07896438]
current_cost: 0.605352856298838
current Theta: [0.02625506 0.0239045  0.07019671 0.08717439]
current_cost: 0.5997879104776551
current Theta: [0.02744276 0.02308025 0.0750807  0.09427773]
current_cost: 0.5952169421217449
current Theta: [0.02828138 0.02173367 0.07921468 0.10056108]
current_cost: 0.5912948822650648
current Theta: [0.02886095 0.02000137 0.08279034 0.10623275]
current_cost: 0.5878091976490675
current Theta: [0.02924751 0.01798356 0.08594824 0.1114454 ]
current_cost: 0.5846251244843197
current Theta: [0.02948978 0

current Theta: [ 0.01366203 -0.25357864  0.27391293  0.48500245]
current_cost: 0.3812198885198906
current Theta: [ 0.01354474 -0.2556272   0.27532184  0.4878087 ]
current_cost: 0.3799436647985124
current Theta: [ 0.01342797 -0.25766978  0.27672706  0.49060735]
current_cost: 0.37867451768675436
current Theta: [ 0.01331171 -0.25970639  0.27812861  0.49339843]
current_cost: 0.3774123995364104
current Theta: [ 0.01319596 -0.26173706  0.27952648  0.49618196]
current_cost: 0.37615726301378805
current Theta: [ 0.01308072 -0.26376182  0.2809207   0.49895798]
current_cost: 0.37490906109865
current Theta: [ 0.01296598 -0.26578069  0.28231127  0.5017265 ]
current_cost: 0.373667747083132
current Theta: [ 0.01285175 -0.2677937   0.28369821  0.50448757]
current_cost: 0.3724332745706595
current Theta: [ 0.01273801 -0.26980088  0.28508154  0.5072412 ]
current_cost: 0.3712055974747951
current Theta: [ 0.01262477 -0.27180225  0.28646125  0.50998743]
current_cost: 0.3699846700181116
current Theta: [ 0.01

current Theta: [ 0.00283542 -0.45717215  0.41572763  0.76646085]
current_cost: 0.2703394294606132
current Theta: [ 0.00276161 -0.45867485  0.41678548  0.76855438]
current_cost: 0.2696362195286223
current Theta: [ 0.00268807 -0.46017392  0.4178409   0.77064306]
current_cost: 0.26893630343248676
current Theta: [ 0.00261479 -0.46166939  0.41889392  0.7727269 ]
current_cost: 0.2682396605497156
current Theta: [ 0.00254177 -0.46316127  0.41994452  0.77480591]
current_cost: 0.2675462704091674
current Theta: [ 0.00246902 -0.46464957  0.42099274  0.77688012]
current_cost: 0.2668561126898729
current Theta: [ 0.00239652 -0.4661343   0.42203856  0.77894955]
current_cost: 0.2661691672198967
current Theta: [ 0.00232429 -0.46761549  0.42308201  0.78101422]
current_cost: 0.2654854139751636
current Theta: [ 0.00225231 -0.46909314  0.42412309  0.78307413]
current_cost: 0.26480483307833835
current Theta: [ 0.0021806  -0.47056727  0.4251618   0.78512931]
current_cost: 0.26412740479767643
current Theta: [ 

current Theta: [-0.00443528 -0.6152764   0.52759201  0.98758096]
current_cost: 0.2047287976233892
current Theta: [-0.00448467 -0.61643272  0.52841329  0.98920308]
current_cost: 0.20430792935922107
current Theta: [-0.0045339  -0.61758678  0.52923299  0.99082206]
current_cost: 0.20388869266228762
current Theta: [-0.00458297 -0.61873856  0.53005111  0.99243791]
current_cost: 0.20347107871589246
current Theta: [-0.0046319  -0.61988809  0.53086765  0.99405064]
current_cost: 0.2030550787623115
current Theta: [-0.00468067 -0.62103537  0.53168263  0.99566027]
current_cost: 0.2026406841023528
current Theta: [-0.00472929 -0.6221804   0.53249603  0.99726679]
current_cost: 0.20222788609490078
current Theta: [-0.00477775 -0.6233232   0.53330788  0.99887023]
current_cost: 0.2018166761564718
current Theta: [-0.00482607 -0.62446377  0.53411818  1.00047059]
current_cost: 0.20140704576076932
current Theta: [-0.00487424 -0.62560213  0.53492692  1.00206788]
current_cost: 0.2009989864382471
current Theta: 

current Theta: [-0.00913006 -0.73228735  0.61079502  1.15190643]
current_cost: 0.16603729845196258
current Theta: [-0.00916535 -0.73323188  0.61146696  1.15323372]
current_cost: 0.16575542410582822
current Theta: [-0.00920054 -0.73417484  0.61213778  1.15455882]
current_cost: 0.16547447677117455
current Theta: [-0.00923563 -0.73511624  0.61280749  1.15588174]
current_cost: 0.16519445210915523
current Theta: [-0.00927062 -0.7360561   0.61347609  1.15720247]
current_cost: 0.16491534580665262
current Theta: [-0.00930551 -0.7369944   0.61414359  1.15852103]
current_cost: 0.1646371535760961
current Theta: [-0.0093403  -0.73793116  0.61480998  1.15983743]
current_cost: 0.16435987115527947
current Theta: [-0.00937498 -0.73886639  0.61547528  1.16115167]
current_cost: 0.16408349430718613
current Theta: [-0.00940957 -0.73980008  0.61613949  1.16246375]
current_cost: 0.16380801881981338
current Theta: [-0.00944406 -0.74073224  0.6168026   1.16377369]
current_cost: 0.163533440505992
current Theta

current Theta: [-0.01249125 -0.82855917  0.6792358   1.2871641 ]
current_cost: 0.13958001118216504
current Theta: [-0.01251698 -0.82935593  0.67980155  1.2882829 ]
current_cost: 0.1393793296246823
current Theta: [-0.01254263 -0.83015156  0.68036648  1.2894001 ]
current_cost: 0.13917921766004976
current Theta: [-0.01256822 -0.83094607  0.6809306   1.2905157 ]
current_cost: 0.13897967295798158
current Theta: [-0.01259373 -0.83173945  0.6814939   1.29162971]
current_cost: 0.13878069320043038
current Theta: [-0.01261917 -0.83253171  0.68205639  1.29274213]
current_cost: 0.13858227608150542
current Theta: [-0.01264453 -0.83332286  0.68261808  1.29385296]
current_cost: 0.13838441930739828
current Theta: [-0.01266983 -0.83411289  0.68317895  1.29496222]
current_cost: 0.1381871205963044
current Theta: [-0.01269506 -0.83490181  0.68373902  1.29606989]
current_cost: 0.1379903776783515
current Theta: [-0.01272021 -0.83568963  0.68429829  1.29717599]
current_cost: 0.13779418829551937
current Theta

current Theta: [-0.01488889 -0.90865592  0.73601058  1.39952646]
current_cost: 0.12077968560201152
current Theta: [-0.01490782 -0.90934638  0.73649895  1.40049387]
current_cost: 0.12062919436374887
current Theta: [-0.0149267  -0.91003598  0.73698669  1.40146005]
current_cost: 0.1204790785372529
current Theta: [-0.01494553 -0.91072473  0.73747381  1.40242502]
current_cost: 0.12032933676130081
current Theta: [-0.0149643  -0.91141262  0.73796031  1.40338876]
current_cost: 0.12017996768105749
current Theta: [-0.01498301 -0.91209967  0.73844618  1.4043513 ]
current_cost: 0.1200309699480369
current Theta: [-0.01500168 -0.91278588  0.73893143  1.40531262]
current_cost: 0.11988234222006718
current Theta: [-0.01502029 -0.91347123  0.73941607  1.40627274]
current_cost: 0.11973408316125296
current Theta: [-0.01503884 -0.91415575  0.73990009  1.40723165]
current_cost: 0.11958619144194119
current Theta: [-0.01505734 -0.91483942  0.74038349  1.40818935]
current_cost: 0.11943866573868708
current Thet

current Theta: [-0.01667161 -0.97988959  0.7862698   1.49918428]
current_cost: 0.10621534600545697
current Theta: [-0.01668526 -0.98049703  0.78669716  1.50003264]
current_cost: 0.10609918391432391
current Theta: [-0.01669888 -0.98110381  0.78712403  1.50088004]
current_cost: 0.10598327913620581
current Theta: [-0.01671245 -0.98170992  0.78755042  1.50172649]
current_cost: 0.10586763083753416
current Theta: [-0.01672598 -0.98231537  0.78797631  1.50257199]
current_cost: 0.10575223818825583
current Theta: [-0.01673946 -0.98292016  0.78840172  1.50341654]
current_cost: 0.10563710036181245
current Theta: [-0.01675291 -0.98352429  0.78882664  1.50426014]
current_cost: 0.10552221653512371
current Theta: [-0.01676631 -0.98412776  0.78925108  1.5051028 ]
current_cost: 0.10540758588857017
current Theta: [-0.01677967 -0.98473058  0.78967503  1.50594451]
current_cost: 0.10529320760597312
current Theta: [-0.016793   -0.98533275  0.7900985   1.50678528]
current_cost: 0.10517908087458037
current Th

current Theta: [-0.01791986 -1.04192641  0.82978737  1.58566894]
current_cost: 0.09500342209967483
current Theta: [-0.01792943 -1.04246959  0.83016716  1.58642465]
current_cost: 0.09491086479825697
current Theta: [-0.01793897 -1.04301225  0.83054656  1.5871796 ]
current_cost: 0.09481849190664628
current Theta: [-0.01794847 -1.04355437  0.83092556  1.58793379]
current_cost: 0.09472630288509723
current Theta: [-0.01795795 -1.04409596  0.83130417  1.5886872 ]
current_cost: 0.0946342971959283
current Theta: [-0.01796739 -1.04463702  0.83168239  1.58943986]
current_cost: 0.09454247430351068
current Theta: [-0.01797679 -1.04517755  0.83206022  1.59019175]
current_cost: 0.09445083367426331
current Theta: [-0.01798616 -1.04571756  0.83243765  1.59094288]
current_cost: 0.09435937477663835
current Theta: [-0.0179955  -1.04625705  0.8328147   1.59169325]
current_cost: 0.09426809708111432
current Theta: [-0.01800481 -1.04679601  0.83319135  1.59244286]
current_cost: 0.09417700006018652
current The

current Theta: [-0.01880819 -1.10065744  0.87070864  1.6672016 ]
current_cost: 0.08552236699688405
current Theta: [-0.01881429 -1.10114608  0.87104781  1.66787833]
current_cost: 0.08544779472694129
current Theta: [-0.01882037 -1.10163429  0.87138666  1.66855445]
current_cost: 0.08537335661670546
current Theta: [-0.01882641 -1.10212208  0.8717252   1.66922994]
current_cost: 0.08529905231031534
current Theta: [-0.01883243 -1.10260944  0.87206341  1.66990481]
current_cost: 0.08522488145314674
current Theta: [-0.01883843 -1.10309637  0.8724013   1.67057905]
current_cost: 0.08515084369180817
current Theta: [-0.01884439 -1.10358287  0.87273887  1.67125268]
current_cost: 0.08507693867413459
current Theta: [-0.01885033 -1.10406895  0.87307612  1.6719257 ]
current_cost: 0.08500316604918268
current Theta: [-0.01885624 -1.1045546   0.87341306  1.67259809]
current_cost: 0.08492952546722504
current Theta: [-0.01886213 -1.10503983  0.87374968  1.67326987]
current_cost: 0.08485601657974674
current Th

current_cost: 0.07886500724305005
current Theta: [-0.01928289 -1.1466119   0.90250197  1.73071439]
current_cost: 0.07880195726783147
current Theta: [-0.01928652 -1.14706179  0.90281214  1.73133481]
current_cost: 0.07873901199858536
current Theta: [-0.01929013 -1.14751131  0.90312203  1.73195469]
current_cost: 0.07867617117830607
current Theta: [-0.01929371 -1.14796048  0.90343165  1.73257405]
current_cost: 0.07861343455081572
current Theta: [-0.01929727 -1.14840928  0.903741    1.73319288]
current_cost: 0.07855080186076285
current Theta: [-0.0193008  -1.14885772  0.90405008  1.73381118]
current_cost: 0.07848827285361894
current Theta: [-0.01930431 -1.1493058   0.90435889  1.73442896]
current_cost: 0.0784258472756727
current Theta: [-0.0193078  -1.14975352  0.90466743  1.73504622]
current_cost: 0.07836352487402949
current Theta: [-0.01931127 -1.15020088  0.9049757   1.73566295]
current_cost: 0.07830130539660729
current Theta: [-0.01931471 -1.15064788  0.9052837   1.73627916]
current_cos

current Theta: [-0.01954758 -1.19321561  0.93450974  1.79482799]
current_cost: 0.07255916015039611
current Theta: [-0.01954889 -1.19362945  0.93479281  1.79539585]
current_cost: 0.07250616771515195
current Theta: [-0.01955019 -1.19404298  0.93507565  1.79596326]
current_cost: 0.07245325623648059
current Theta: [-0.01955147 -1.1944562   0.93535827  1.79653023]
current_cost: 0.0724004255311688
current Theta: [-0.01955272 -1.19486911  0.93564065  1.79709675]
current_cost: 0.07234767541654911
current Theta: [-0.01955396 -1.19528173  0.9359228   1.79766282]
current_cost: 0.07229500571049802
current Theta: [-0.01955518 -1.19569403  0.93620472  1.79822845]
current_cost: 0.0722424162314335
current Theta: [-0.01955638 -1.19610604  0.93648642  1.79879364]
current_cost: 0.0721899067983141
current Theta: [-0.01955756 -1.19651774  0.93676788  1.79935838]
current_cost: 0.07213747723063595
current Theta: [-0.01955872 -1.19692913  0.93704912  1.79992268]
current_cost: 0.07208512734843077
current Theta

current Theta: [-0.01958095 -1.23661298  0.96407522  1.85422556]
current_cost: 0.0672238511031371
current Theta: [-0.01958028 -1.23699597  0.96433503  1.85474833]
current_cost: 0.06717870890642942
current Theta: [-0.0195796  -1.23737869  0.96459464  1.85527072]
current_cost: 0.06713363053150205
current Theta: [-0.01957889 -1.23776115  0.96485405  1.85579272]
current_cost: 0.06708861584444135
current Theta: [-0.01957817 -1.23814336  0.96511326  1.85631435]
current_cost: 0.06704366471170517
current Theta: [-0.01957743 -1.2385253   0.96537228  1.85683559]
current_cost: 0.06699877700011982
current Theta: [-0.01957668 -1.23890698  0.9656311   1.85735646]
current_cost: 0.06695395257688026
current Theta: [-0.0195759  -1.23928841  0.96588973  1.85787695]
current_cost: 0.06690919130954803
current Theta: [-0.01957512 -1.23966957  0.96614816  1.85839705]
current_cost: 0.06686449306604952
current Theta: [-0.01957431 -1.24005048  0.96640639  1.85891678]
current_cost: 0.06681985771467612
current The

current_cost: 0.06284810046967423
current Theta: [-0.01942251 -1.27546617  0.99032604  1.90712444]
current_cost: 0.06280894058444658
current Theta: [-0.01942019 -1.27582361  0.99056652  1.90760979]
current_cost: 0.0627698323693655
current Theta: [-0.01941785 -1.27618083  0.99080682  1.90809481]
current_cost: 0.0627307757231008
current Theta: [-0.01941549 -1.27653782  0.99104696  1.9085795 ]
current_cost: 0.06269177054458425
current Theta: [-0.01941313 -1.27689458  0.99128692  1.90906385]
current_cost: 0.06265281673300915
current Theta: [-0.01941074 -1.27725112  0.99152671  1.90954787]
current_cost: 0.0626139141878297
current Theta: [-0.01940834 -1.27760743  0.99176634  1.91003157]
current_cost: 0.06257506280876025
current Theta: [-0.01940593 -1.27796352  0.99200579  1.91051493]
current_cost: 0.0625362624957733
current Theta: [-0.0194035  -1.27831938  0.99224507  1.91099797]
current_cost: 0.06249751314910041
current Theta: [-0.01940106 -1.27867502  0.99248418  1.91148067]
current_cost: 

current Theta: [-0.01908254 -1.31348903  1.0157958   1.95861129]
current_cost: 0.05879579332114253
current Theta: [-0.01907871 -1.31382325  1.01601865  1.95906254]
current_cost: 0.058761803746266154
current Theta: [-0.01907486 -1.31415726  1.01624135  1.9595135 ]
current_cost: 0.05872785602673297
current Theta: [-0.019071   -1.31449109  1.01646391  1.95996417]
current_cost: 0.05869395008583815
current Theta: [-0.01906712 -1.31482471  1.01668631  1.96041456]
current_cost: 0.05866008584706251
current Theta: [-0.01906324 -1.31515814  1.01690856  1.96086465]
current_cost: 0.058626263234072135
current Theta: [-0.01905933 -1.31549137  1.01713067  1.96131446]
current_cost: 0.058592482170717206
current Theta: [-0.01905542 -1.31582441  1.01735263  1.96176398]
current_cost: 0.05855874258103261
current Theta: [-0.0190515  -1.31615725  1.01757444  1.96221321]
current_cost: 0.0585250443892376
current Theta: [-0.01904756 -1.3164899   1.0177961   1.96266216]
current_cost: 0.05849138751973313
current 

current Theta: [-0.01859701 -1.34849465  1.03903519  2.0057441 ]
current_cost: 0.055352036931645775
current Theta: [-0.01859186 -1.34880893  1.03924288  2.00616603]
current_cost: 0.05532215968916747
current Theta: [-0.01858671 -1.34912304  1.03945044  2.0065877 ]
current_cost: 0.05529231698757984
current Theta: [-0.01858155 -1.34943698  1.03965786  2.00700912]
current_cost: 0.055262508767391166
current Theta: [-0.01857638 -1.34975074  1.03986515  2.00743029]
current_cost: 0.05523273496924523
current Theta: [-0.01857119 -1.35006433  1.04007231  2.0078512 ]
current_cost: 0.055202995533921266
current Theta: [-0.01856599 -1.35037775  1.04027934  2.00827186]
current_cost: 0.05517329040233333
current Theta: [-0.01856078 -1.350691    1.04048624  2.00869227]
current_cost: 0.05514361951552945
current Theta: [-0.01855557 -1.35100407  1.04069301  2.00911242]
current_cost: 0.055113982814692465
current Theta: [-0.01855033 -1.35131698  1.04089964  2.00953232]
current_cost: 0.055084380241138826
curre

current Theta: [-0.01799759 -1.38058597  1.06014987  2.04870882]
current_cost: 0.052392980567380974
current Theta: [-0.01799133 -1.38088313  1.06034449  2.04910552]
current_cost: 0.05236642899763025
current Theta: [-0.01798505 -1.38118013  1.060539    2.04950199]
current_cost: 0.052339906396365515
current Theta: [-0.01797876 -1.38147698  1.06073339  2.04989823]
current_cost: 0.05231341271645926
current Theta: [-0.01797247 -1.38177368  1.06092767  2.05029425]
current_cost: 0.052286947910886214
current Theta: [-0.01796616 -1.38207022  1.06112182  2.05069004]
current_cost: 0.05226051193272203
current Theta: [-0.01795984 -1.38236661  1.06131587  2.05108561]
current_cost: 0.05223410473514353
current Theta: [-0.01795352 -1.38266285  1.06150979  2.05148095]
current_cost: 0.052207726271428084
current Theta: [-0.01794718 -1.38295893  1.0617036   2.05187606]
current_cost: 0.052181376494953746
current Theta: [-0.01794083 -1.38325486  1.06189729  2.05227095]
current_cost: 0.052155055359198205
curr

current Theta: [-0.01724243 -1.41266796  1.08106394  2.09141075]
current_cost: 0.04961273064213405
current Theta: [-0.0172351  -1.41294903  1.08124627  2.0917837 ]
current_cost: 0.049589127865345334
current Theta: [-0.01722776 -1.41322996  1.0814285   2.09215646]
current_cost: 0.049565549390430445
current Theta: [-0.01722042 -1.41351075  1.08161062  2.09252901]
current_cost: 0.04954199518005054
current Theta: [-0.01721306 -1.41379141  1.08179264  2.09290136]
current_cost: 0.04951846519694201
current Theta: [-0.01720569 -1.41407194  1.08197455  2.09327351]
current_cost: 0.049494959403917835
current Theta: [-0.01719832 -1.41435233  1.08215636  2.09364546]
current_cost: 0.04947147776386639
current Theta: [-0.01719093 -1.41463258  1.08233807  2.09401721]
current_cost: 0.049448020239751436
current Theta: [-0.01718354 -1.4149127   1.08251967  2.09438875]
current_cost: 0.04942458679461201
current Theta: [-0.01717614 -1.41519268  1.08270117  2.0947601 ]
current_cost: 0.04940117739156271
curren

current Theta: [-0.01636723 -1.44332983  1.10085882  2.13197314]
current_cost: 0.0471122175623949
current Theta: [-0.01635894 -1.44359644  1.10103007  2.13232472]
current_cost: 0.04709112070598906
current Theta: [-0.01635064 -1.44386293  1.10120123  2.13267612]
current_cost: 0.04707004440167392
current Theta: [-0.01634234 -1.44412929  1.1013723   2.13302734]
current_cost: 0.04704898861955212
current Theta: [-0.01633402 -1.44439553  1.10154327  2.13337837]
current_cost: 0.04702795332978424
current Theta: [-0.0163257  -1.44466165  1.10171415  2.13372923]
current_cost: 0.0470069385025881
current Theta: [-0.01631737 -1.44492765  1.10188494  2.13407991]
current_cost: 0.04698594410823954
current Theta: [-0.01630903 -1.44519352  1.10205564  2.13443041]
current_cost: 0.04696497011707102
current Theta: [-0.01630068 -1.44545928  1.10222624  2.13478073]
current_cost: 0.04694401649947231
current Theta: [-0.01629233 -1.44572491  1.10239675  2.13513087]
current_cost: 0.04692308322589033
current Thet

current Theta: [-0.01543555 -1.47118776  1.11866984  2.16860211]
current_cost: 0.044965754372506765
current Theta: [-0.01542644 -1.47144196  1.11883157  2.16893532]
current_cost: 0.044946697819044486
current Theta: [-0.01541731 -1.47169605  1.11899322  2.16926837]
current_cost: 0.044927658920277926
current Theta: [-0.01540818 -1.47195002  1.11915478  2.16960126]
current_cost: 0.04490863765177054
current Theta: [-0.01539904 -1.47220389  1.11931626  2.16993398]
current_cost: 0.04488963398913043
current Theta: [-0.01538989 -1.47245765  1.11947765  2.17026654]
current_cost: 0.04487064790801031
current Theta: [-0.01538073 -1.4727113   1.11963896  2.17059894]
current_cost: 0.04485167938410773
current Theta: [-0.01537157 -1.47296484  1.11980019  2.17093118]
current_cost: 0.04483272839316524
current Theta: [-0.0153624  -1.47321826  1.11996133  2.17126325]
current_cost: 0.044813794910969096
current Theta: [-0.01535322 -1.47347158  1.12012239  2.17159516]
current_cost: 0.044794878913350426
curre

current Theta: [-0.01433026 -1.49996507  1.13688545  2.20620328]
current_cost: 0.042867063028408176
current Theta: [-0.01432033 -1.50020714  1.13703786  2.20651852]
current_cost: 0.042849902112828075
current Theta: [-0.01431039 -1.50044911  1.13719019  2.20683362]
current_cost: 0.04283275629258559
current Theta: [-0.01430044 -1.50069098  1.13734245  2.20714856]
current_cost: 0.04281562554783246
current Theta: [-0.01429049 -1.50093276  1.13749463  2.20746336]
current_cost: 0.04279850985875495
current Theta: [-0.01428054 -1.50117443  1.13764674  2.20777802]
current_cost: 0.0427814092055742
current Theta: [-0.01427057 -1.50141601  1.13779877  2.20809253]
current_cost: 0.04276432356854553
current Theta: [-0.0142606  -1.50165749  1.13795072  2.20840689]
current_cost: 0.04274725292795869
current Theta: [-0.01425062 -1.50189887  1.1381026   2.2087211 ]
current_cost: 0.04273019726413815
current Theta: [-0.01424064 -1.50214015  1.1382544   2.20903517]
current_cost: 0.04271315655744247
current T

current_cost: 0.041018968720859125
current Theta: [-0.01315644 -1.52694308  1.15378439  2.24122369]
current_cost: 0.0410033956342881
current Theta: [-0.01314578 -1.52717439  1.15392851  2.24152296]
current_cost: 0.04098783560306301
current Theta: [-0.01313512 -1.5274056   1.15407257  2.2418221 ]
current_cost: 0.04097228861081732
current Theta: [-0.01312445 -1.52763673  1.15421655  2.2421211 ]
current_cost: 0.04095675464121244
current Theta: [-0.01311378 -1.52786778  1.15436047  2.24241997]
current_cost: 0.04094123367793643
current Theta: [-0.0131031  -1.52809873  1.15450431  2.24271871]
current_cost: 0.04092572570470445
current Theta: [-0.01309241 -1.52832959  1.15464809  2.24301732]
current_cost: 0.040910230705259336
current Theta: [-0.01308172 -1.52856036  1.1547918   2.24331579]
current_cost: 0.04089474866337046
current Theta: [-0.01307102 -1.52879104  1.15493544  2.24361413]
current_cost: 0.04087927956283424
current Theta: [-0.01306031 -1.52902163  1.15507901  2.24391234]
current_c

current Theta: [-0.01207276 -1.54941853  1.16772552  2.27022152]
current_cost: 0.03952374040449741
current Theta: [-0.01206152 -1.5496413   1.16786306  2.27050811]
current_cost: 0.03950939603606736
current Theta: [-0.01205028 -1.54986399  1.16800054  2.27079457]
current_cost: 0.039495063212677844
current Theta: [-0.01203904 -1.55008659  1.16813795  2.27108091]
current_cost: 0.03948074192042996
current Theta: [-0.01202779 -1.55030912  1.16827529  2.27136713]
current_cost: 0.039466432145447095
current Theta: [-0.01201653 -1.55053156  1.16841258  2.27165323]
current_cost: 0.03945213387387498
current Theta: [-0.01200527 -1.55075391  1.16854979  2.2719392 ]
current_cost: 0.03943784709188096
current Theta: [-0.011994   -1.55097619  1.16868695  2.27222505]
current_cost: 0.03942357178565526
current Theta: [-0.01198273 -1.55119838  1.16882404  2.27251078]
current_cost: 0.039409307941409615
current Theta: [-0.01197145 -1.55142049  1.16896107  2.27279638]
current_cost: 0.03939505554537798
current

current Theta: [-0.0108161  -1.57322706  1.18235157  2.30075554]
current_cost: 0.038025359269994674
current Theta: [-0.01080428 -1.57344119  1.18248243  2.30102927]
current_cost: 0.03801219593661239
current Theta: [-0.01079245 -1.57365524  1.18261324  2.3013029 ]
current_cost: 0.03799904275545557
current Theta: [-0.01078062 -1.57386922  1.18274398  2.30157641]
current_cost: 0.03798589971480903
current Theta: [-0.01076878 -1.57408312  1.18287467  2.3018498 ]
current_cost: 0.037972766802976114
current Theta: [-0.01075694 -1.57429694  1.1830053   2.30212309]
current_cost: 0.03795964400827825
current Theta: [-0.01074509 -1.57451069  1.18313587  2.30239626]
current_cost: 0.03794653131905391
current Theta: [-0.01073324 -1.57472437  1.18326638  2.30266932]
current_cost: 0.03793342872366025
current Theta: [-0.01072138 -1.57493797  1.18339684  2.30294227]
current_cost: 0.03792033621047186
current Theta: [-0.01070952 -1.57515149  1.18352723  2.3032151 ]
current_cost: 0.0379072537678812
current T

current Theta: [-0.0095474  -1.59530694  1.19578016  2.32889711]
current_cost: 0.03669652708251564
current Theta: [-0.00953505 -1.59551341  1.1959051   2.32915945]
current_cost: 0.0366843689824581
current Theta: [-0.00952271 -1.59571981  1.19602998  2.32942168]
current_cost: 0.03667221989662841
current Theta: [-0.00951035 -1.59592614  1.19615482  2.32968381]
current_cost: 0.03666007981502514
current Theta: [-0.009498   -1.5961324   1.19627959  2.32994583]
current_cost: 0.03664794872766185
current Theta: [-0.00948563 -1.59633859  1.19640432  2.33020775]
current_cost: 0.036635826624566915
current Theta: [-0.00947327 -1.59654471  1.19652899  2.33046957]
current_cost: 0.03662371349578322
current Theta: [-0.0094609  -1.59675076  1.1966536   2.33073128]
current_cost: 0.03661160933136835
current Theta: [-0.00944852 -1.59695674  1.19677817  2.33099288]
current_cost: 0.036599514121394575
current Theta: [-0.00943614 -1.59716265  1.19690267  2.33125439]
current_cost: 0.03658742785594884
current T

current Theta: [-0.00809742 -1.61860433  1.20980251  2.35840039]
current_cost: 0.03535506251688061
current Theta: [-0.00808455 -1.61880308  1.20992147  2.35865122]
current_cost: 0.03534387896025083
current Theta: [-0.00807168 -1.61900176  1.21004037  2.35890195]
current_cost: 0.03533270335814593
current Theta: [-0.0080588  -1.61920037  1.21015923  2.35915258]
current_cost: 0.03532153570209802
current Theta: [-0.00804591 -1.61939892  1.21027804  2.35940312]
current_cost: 0.03531037598365113
current Theta: [-0.00803302 -1.61959741  1.2103968   2.35965356]
current_cost: 0.0352992241943612
current Theta: [-0.00802013 -1.61979583  1.21051551  2.3599039 ]
current_cost: 0.035288080325796244
current Theta: [-0.00800723 -1.61999419  1.21063416  2.36015415]
current_cost: 0.03527694436953577
current Theta: [-0.00799433 -1.62019248  1.21075277  2.36040431]
current_cost: 0.03526581631717198
current Theta: [-0.00798142 -1.62039071  1.21087133  2.36065436]
current_cost: 0.03525469616030813
current Th

current Theta: [-0.00661572 -1.64066541  1.22293694  2.38615167]
current_cost: 0.034139748556571044
current Theta: [-0.00660237 -1.64085716  1.22305048  2.38639206]
current_cost: 0.03412941295387196
current Theta: [-0.00658901 -1.64104885  1.22316396  2.38663237]
current_cost: 0.034119084420033315
current Theta: [-0.00657565 -1.64124048  1.2232774   2.38687258]
current_cost: 0.03410876294781864
current Theta: [-0.00656229 -1.64143205  1.2233908   2.38711271]
current_cost: 0.03409844853000086
current Theta: [-0.00654892 -1.64162357  1.22350415  2.38735275]
current_cost: 0.03408814115936291
current Theta: [-0.00653555 -1.64181502  1.22361745  2.3875927 ]
current_cost: 0.03407784082869767
current Theta: [-0.00652217 -1.64200641  1.22373071  2.38783256]
current_cost: 0.03406754753080755
current Theta: [-0.00650879 -1.64219774  1.22384392  2.38807234]
current_cost: 0.03405726125850505
current Theta: [-0.00649541 -1.64238902  1.22395708  2.38831202]
current_cost: 0.03404698200461254
current 

In [205]:
test_data = iris2_data[:,:4]
Theta_trained = np.array([-0.00594319, -1.65018081 , 1.2285577,   2.39806382])

In [206]:
print(iris2_data[:10])

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]]


In [214]:
predict_data = np.reshape(feedforward_fun(Theta_trained,test_data),-1,1)

In [216]:
print(predict_data.shape)

(100,)


In [217]:
print(iris2_data.shape)

(100, 5)


In [218]:
iris2_data_trained = np.column_stack((iris2_data,predict_data))

In [219]:
print(iris2_data_trained[:10])

[[5.1        3.5        1.4        0.2        0.         0.0264331 ]
 [4.9        3.         1.4        0.2        0.         0.05841068]
 [4.7        3.2        1.3        0.2        0.         0.03798737]
 [4.6        3.1        1.5        0.2        0.         0.05622906]
 [5.         3.6        1.4        0.2        0.         0.02251561]
 [5.4        3.9        1.7        0.4        0.         0.03167547]
 [4.6        3.4        1.4        0.3        0.         0.03922019]
 [5.         3.4        1.5        0.2        0.         0.03496282]
 [4.4        2.9        1.4        0.2        0.         0.06836495]
 [4.9        3.1        1.5        0.1        0.         0.04470054]]


In [223]:
precision = np.sum(abs(iris2_data_trained[:,4]-iris2_data_trained[:,5])<=0.1)/iris2_data_trained.shape[0]

In [225]:
print('precision:{:.2%}'.format(precision))

precision:97.00%
