In [4]:
import numpy as np

In [5]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
print(iris[:5])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']]


In [6]:
iris[:,:4] = iris[:,:4].astype(np.float)
iris[:,4] = iris[:,4].astype(np.str)

In [7]:
iris.shape

(150, 5)

In [8]:
print(iris[:5])

[[5.1 3.5 1.4 0.2 'Iris-setosa']
 [4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 [4.6 3.1 1.5 0.2 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']]


In [9]:
class Node:
    def __init__(self,X=None,left_node=None,right_node=None):
        self.X = X
        self.left_node = left_node
        self.right_node = right_node
    
    def __repr__(self):
        return 'X:{};left_node:{};right_node:{}'.format(self.X,self.left_node,self.right_node)
    
    def __str__(self):
        return 'X:{};left_node:{};right_node:{}'.format(self.X,self.left_node,self.right_node)

In [10]:
node_root = Node([1,2])
node_left = Node([3,2])
node_right = Node([1,1])
node_root.left_node = node_left
node_root.right_node = node_right

In [11]:
print(node_root)

X:[1, 2];left_node:X:[3, 2];left_node:None;right_node:None;right_node:X:[1, 1];left_node:None;right_node:None


In [12]:
iris[iris[:,0] == 4.3]

array([[4.3, 3.0, 1.1, 0.1, 'Iris-setosa']], dtype=object)

In [13]:
vector = np.array([1,2,4,2,1])
print()
median_value = 2
np.min(abs(vector - median_value))

0

In [14]:
vector[vector - median_value == 0]

array([2, 2])

In [33]:
len(np.array([]))

0

In [50]:
def create_kdtree(node, X_list, count):
    if X_list.shape[0]<= 1:
        return None 
    node = Node()
    index = count%4
    median_value = np.median(X_list[:,index])
    minimum_value = np.min(abs(X_list[:,index] - median_value))
    median_x = X_list[:,index - median_value == minimum_value]
    
    node.X = median_x
    left_X = X_list[X_list[:,index]< median_value]
    right_X = X_list[X_list[:,index]> median_value]
    count += 1
    
    node.left_node = create_kdtree(None,left_X, count)
    node.right_node = create_kdtree(None,right_X, count)
    return node

In [51]:
kd_tree = create_kdtree(None,iris,0)

In [36]:
iris[:5]

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa']], dtype=object)

In [37]:
iris[iris[:,1]>1000]

array([], shape=(0, 5), dtype=object)

In [44]:
np.array([]).shape

(0,)