In [1]:
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [2]:
print(iris[:10])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [3]:
print(np.unique(iris[:,4]))

[b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica']


In [5]:
iris2 = iris[(iris[:,4] == b'Iris-setosa') | (iris[:,4] == b'Iris-virginica')]

In [6]:
np.unique(iris2[:,4])

array([b'Iris-setosa', b'Iris-virginica'], dtype=object)

In [38]:
label_setosa = -1* np.ones([np.shape(iris2[iris2[:,4] ==  b'Iris-setosa'])[0],1])

In [39]:
print(label_setosa[:5])

[[-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]]


In [60]:
label_virginica = np.ones([np.shape(iris2[iris2[:,4] ==  b'Iris-virginica'])[0],1])

In [61]:
print(label_virginica[:5])

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [62]:
setosa_data = np.hstack((iris2[iris2[:,4]==b'Iris-setosa'],label_setosa))

In [63]:
virginica_data = np.hstack((iris2[iris2[:,4]==b'Iris-virginica'],label_virginica))

In [64]:
print(setosa_data[:5])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa' -1.0]
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa' -1.0]
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa' -1.0]
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa' -1.0]
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa' -1.0]]


In [65]:
print(virginica_data[:5])

[[b'6.3' b'3.3' b'6.0' b'2.5' b'Iris-virginica' 1.0]
 [b'5.8' b'2.7' b'5.1' b'1.9' b'Iris-virginica' 1.0]
 [b'7.1' b'3.0' b'5.9' b'2.1' b'Iris-virginica' 1.0]
 [b'6.3' b'2.9' b'5.6' b'1.8' b'Iris-virginica' 1.0]
 [b'6.5' b'3.0' b'5.8' b'2.2' b'Iris-virginica' 1.0]]


In [66]:
iris2_data = np.vstack((setosa_data,virginica_data))

In [67]:
print(iris2_data[:5])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa' -1.0]
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa' -1.0]
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa' -1.0]
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa' -1.0]
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa' -1.0]]


In [68]:
print(iris2_data.shape)

(100, 6)


In [69]:
sampling_indexs = np.random.choice(iris2_data.shape[0],80)

In [70]:
iris2_train = iris2_data[sampling_indexs]

In [71]:
X = iris2_train[:,:4].astype(np.float)

In [72]:
print(X[:5])

[[6.4 2.7 5.3 1.9]
 [5.2 3.5 1.5 0.2]
 [6.1 2.6 5.6 1.4]
 [6.7 2.5 5.8 1.8]
 [6.3 2.5 5.  1.9]]


In [87]:
Y = iris2_train[:,5].reshape(-1,1)

In [89]:
print(Y.shape[0])
print(Y[])

80


In [90]:
print(np.unique(Y))

[-1.0 1.0]


In [97]:
X[1]
np.zeros([4,])

array([0., 0., 0., 0.])

In [101]:
if __name__ == "__main__":
    
    W = np.zeros([4,])
    b = 0
    learning_rate = 0.01
    for i in range(Y.shape[0]):
        judge_criterion = (np.dot(W,X[i])+b)*Y[i] 
        if judge_criterion <= 0:
            W = W + learning_rate*Y[i]*X[i]
            b = b+Y[i]
            i = 0
    print('W:',W)
    print('b:',b)

W: [0.03699999999999999 -0.05600000000000001 0.188 0.075]
b: [-1.0]


In [102]:
W = np.array([0.05799999999999998,-0.029000000000000005,0.16099999999999998,0.059])
b=-1

In [104]:
def forward_fun():
    result = []
    for x in X:
        judge_criterion = (np.dot(W,X[i])+b)*Y[i]
        result.append(judge_criterion)
    return np.array(result)

In [108]:
np.all(forward_fun()>0)

True