In [1]:
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [2]:
print(iris[:10])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [3]:
print(np.unique(iris[:,4]))

[b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica']


In [4]:
iris2 = iris[(iris[:,4] == b'Iris-setosa') | (iris[:,4] == b'Iris-virginica')]

In [5]:
np.unique(iris2[:,4])

array([b'Iris-setosa', b'Iris-virginica'], dtype=object)

In [6]:
label_setosa = -1* np.ones([np.shape(iris2[iris2[:,4] ==  b'Iris-setosa'])[0],1])

In [7]:
print(label_setosa[:5])

[[-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]]


In [8]:
label_virginica = np.ones([np.shape(iris2[iris2[:,4] ==  b'Iris-virginica'])[0],1])

In [9]:
print(label_virginica[:5])

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [10]:
setosa_data = np.hstack((iris2[iris2[:,4]==b'Iris-setosa'],label_setosa))

In [11]:
virginica_data = np.hstack((iris2[iris2[:,4]==b'Iris-virginica'],label_virginica))

In [12]:
print(setosa_data[:5])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa' -1.0]
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa' -1.0]
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa' -1.0]
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa' -1.0]
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa' -1.0]]


In [13]:
print(virginica_data[:5])

[[b'6.3' b'3.3' b'6.0' b'2.5' b'Iris-virginica' 1.0]
 [b'5.8' b'2.7' b'5.1' b'1.9' b'Iris-virginica' 1.0]
 [b'7.1' b'3.0' b'5.9' b'2.1' b'Iris-virginica' 1.0]
 [b'6.3' b'2.9' b'5.6' b'1.8' b'Iris-virginica' 1.0]
 [b'6.5' b'3.0' b'5.8' b'2.2' b'Iris-virginica' 1.0]]


In [14]:
iris2_data = np.vstack((setosa_data,virginica_data))

In [15]:
print(iris2_data[:5])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa' -1.0]
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa' -1.0]
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa' -1.0]
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa' -1.0]
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa' -1.0]]


In [16]:
print(iris2_data.shape)

(100, 6)


In [17]:
sampling_indexs = np.random.choice(iris2_data.shape[0],80)

In [18]:
iris2_train = iris2_data[sampling_indexs]

In [19]:
X = iris2_train[:,:4].astype(np.float)

In [20]:
print(X[:5])

[[6.4 2.8 5.6 2.1]
 [5.5 3.5 1.3 0.2]
 [4.9 3.  1.4 0.2]
 [5.  3.4 1.6 0.4]
 [7.7 2.8 6.7 2. ]]


In [21]:
Y = iris2_train[:,5].reshape(-1,1)

In [22]:
print(Y.shape[0])
# print(Y[])

80


In [23]:
print(np.unique(Y))

[-1.0 1.0]


In [24]:
X[1]
np.zeros([4,])

array([0., 0., 0., 0.])

In [75]:
if __name__ == "__main__":
    
    W = np.zeros([4,])
    b = 0
    learning_rate = 1
    count = 0
    while count < Y.shape[0]:
        print(count)
        judge_criterion = (np.dot(W,X[count])+b)*Y[count] 
        if judge_criterion <= 0:
            W = W + learning_rate*Y[count]*X[count]
            b = b+Y[count]
            count = 0
            continue
        count = count + 1
    print('W:',W)
    print('b:',b)

0
0
1
0
1
0
0
1
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
W: [-3.6999999999999993 -4.9 7.3 3.6]
b: [-1.0]


In [76]:
W = np.array([-3.6999999999999993 ,-4.9, 7.3, 3.6])
b=-1

In [77]:
def sign_fun(x):
    if x<0:
        return -1
    else:
        return 1

In [85]:
def forward_fun(X):
    result = []
    for i in range(X.shape[0]):
        judge_criterion = (np.dot(W,X[i])+b)
        result.append(sign_fun(judge_criterion))
    return np.array(result)

In [89]:
result = forward_fun(iris2_data[:,:4].astype(np.float))

In [93]:
print(result)

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1]


In [95]:
result = np.column_stack((iris2_data,result))

In [97]:
result[:,5] == result[:,6]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])